### ISSUE TITLE
Allow manual specification of `pkgver`

### ISSUE THREAD

**Issue by AladW** [bcyran/bumper#6]
When an upstream provider is not available (e.g. #5), it would be convenient if `pkgver` can be specified on the `bumper` command-line.

**Comment by bcyran** [comment]
Implemented as `--override` / `-o` CLI option, e.g.:
```shell
bumper -o mypackage=1.2.3 -otherpackage=3.2.1
```

**Comment by bcyran** [comment]
Included in release [0.3.0](https://github.com/bcyran/bumper/releases/tag/v0.3.0), AUR package bumped.
