### ISSUE TITLE
Commit credentials in `config.yaml`

### ISSUE THREAD

**Issue by AladW** [bcyran/bumper#8]
The case of people using different git credentials for AUR is common enough, and [sometimes leads to accidents](https://wiki.archlinux.org/title/AUR_Trusted_User_guidelines#Rewriting_git_history). 

`bumper` could include a `git` `user.name` and `user.email` in its configuration file, and pass them on to `git-commit` with `--author=user.name <user.email>` to address this.

**Comment by bcyran** [comment]
Included in release [0.3.0](https://github.com/bcyran/bumper/releases/tag/v0.3.0), AUR package bumped.
